baseURL = "https://example.com"
languageCode = "fr-fr"
defaultContentLanguage = "en"
title = "PaperCSS"
theme = "papercss-hugo-theme"
googleAnalytics = "UA-123456789-1"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[tags]
  tag = "hello"

[params]
  homeMetaContent = "A Hugo theme made with PaperCSS, the less formal CSS framework."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Friday, March 3, 2017"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Chien"
    url = "/chien/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
