baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "fr"
title = "Blog d'un millénial"
theme = "papercss-hugo-theme"


[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99


[params]
  homeMetaContent = "A Hugo theme made with PaperCSS, the less formal CSS framework."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2 Jan, 2006"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
